[package]
name = "rust-chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_chess"
crate-type = ["cdylib"]

[dependencies]
chess = "3.2.0"
pyo3 = "0.24.0"

[lints.clippy]
pedantic = "warn"
