# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

class Board:
    r"""
    Board class
    """
    halfmove_clock: builtins.int
    r"""
    Get the halfmove clock.
    
    ```python
    >>> rust_chess.Board().halfmove_clock
    0
    ```
    """
    fullmove_number: builtins.int
    r"""
    Get the fullmove number.
    
    ```python
    >>> rust_chess.Board().fullmove_number
    1
    ```
    """
    turn: Color
    r"""
    Get the current player to move
    """
    en_passant: typing.Optional[Square]
    r"""
    Get the en passant square, otherwise None
    """
    def __new__(cls, fen:typing.Optional[builtins.str]=None) -> Board:
        r"""
        Create a new board from a FEN string, otherwise default to the starting position
        """
    def get_fen(self) -> builtins.str:
        r"""
        Get the FEN string representation of the board.
        
        ```python
        >>> rust_chess.Board().get_fen()
        'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'
        ```
        """
    def __str__(self) -> builtins.str:
        r"""
        Get the FEN string representation of the board.
        
        ```python
        >>> print(rust_chess.Board())
        rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
        ```
        """
    def __repr__(self) -> builtins.str:
        r"""
        Get the FEN string representation of the board.
        
        ```python
        >>> print(rust_chess.Board())
        rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
        ```
        """
    @staticmethod
    def from_fen(fen:builtins.str) -> Board:
        r"""
        Create a new board from a FEN string
        """
    def is_fifty_moves(self) -> builtins.bool:
        r"""
        Checks if the halfmoves since the last pawn move or capture is >= 100
        and the game is ongoing (not checkmate or stalemate)
        """
    def is_check(self) -> builtins.bool:
        r"""
        Checks if the side to move is in check
        """
    def get_piece_type_on(self, square:Square) -> typing.Optional[PieceType]:
        r"""
        Get the piece type on a square, otherwise None
        """
    def get_color_on(self, square:Square) -> typing.Optional[Color]:
        r"""
        Get the color of the piece on a square, otherwise None
        """
    def get_piece_on(self, square:Square) -> typing.Optional[Piece]:
        r"""
        Get the piece on a square, otherwise None
        """
    def is_legal_move(self, chess_move:Move) -> builtins.bool:
        r"""
        Check if the move is legal (supposedly slow according to the chess crate)
        """
    def is_zeroing(self, chess_move:Move) -> builtins.bool:
        r"""
        Check if a move is a capture or a pawn move (doesn't check for legality)
        """
    def make_move_new(self, chess_move:Move, check_legality:builtins.bool=False) -> Board:
        r"""
        Makes a move onto a new board (around 2x faster than `make_move`)
        """
    def make_move(self, chess_move:Move, check_legality:builtins.bool=False) -> None:
        r"""
        Makes a move on the current board (around 2x slower than `make_move_new`)
        """

class Color:
    r"""
    Color enum class.
    
    ```python
    >>> color = rust_chess.WHITE
    
    >>> color
    True
    >>> print(color)
    WHITE
    >>> color == rust_chess.BLACK
    False
    >>> color == (not rust_chess.BLACK)
    True
    ```
    """
    def get_string(self) -> builtins.str:
        r"""
        Get the color as a string.
        
        ```python
        >>> rust_chess.WHITE.get_string()
        'WHITE'
        >>> rust_chess.BLACK.get_string()
        'BLACK'
        ```
        """
    def __str__(self) -> builtins.str:
        r"""
        Get the color as a string.
        
        ```python
        >>> print(rust_chess.WHITE)
        WHITE
        >>> print(rust_chess.BLACK)
        BLACK
        ```
        """
    def __bool__(self) -> builtins.bool:
        r"""
        Get the color as a boolean.
        
        ```python
        >>> bool(rust_chess.WHITE)
        True
        >>> bool(rust_chess.BLACK)
        False
        ```
        """
    def __repr__(self) -> builtins.str:
        r"""
        Get the color as a bool string.
        
        ```python
        >>> rust_chess.WHITE
        True
        >>> rust_chess.BLACK
        False
        ```
        """
    def __eq__(self, other:typing.Any) -> builtins.bool:
        r"""
        Compare the color to another color or boolean.
        
        ```python
        >>> rust_chess.WHITE == rust_chess.BLACK
        False
        >>> rust_chess.WHITE == True
        True
        ```
        """

class Move:
    r"""
    Move class.
    
    ```python
    >>> move = rust_chess.Move(rust_chess.A4, rust_chess.B1)
    >>> move
    Move(a4, b1, None)
    >>> print(move)
    a4b1
    >>> rust_chess.Move("a2a1q")
    Move(a2, a1, QUEEN)
    >>> move.get_uci() == rust_chess.Move.from_uci("a4b1") // FIXME
    True
    >>> move.source
    a2
    >>> move.dest
    a4
    >>> move.promotion
    
    >>> move.promotion == None
    True
    ```
    """
    source: Square
    r"""
    Get the source square of the move.
    
    ```python
    >>> move = rust_chess.Move(rust_chess.A2, rust_chess.A4)
    >>> move.source
    a2
    ```
    """
    dest: Square
    r"""
    Get the destination square of the move.
    
    
    ```python
    >>> move = rust_chess.Move(rust_chess.A2, rust_chess.A4)
    >>> move.dest
    a4
    ```
    """
    promotion: typing.Optional[PieceType]
    r"""
    Get the promotion piece of the move
    
    ```python
    >>> move = rust_chess.Move(rust_chess.A2, rust_chess.A4)
    >>> move.promotion
    
    >>> move.promotion == None
    True
    ```
    """
    def __new__(cls, source_or_uci:typing.Any, dest:typing.Optional[Square]=None, promotion:typing.Optional[PieceType]=None) -> Move:
        r"""
        Create a new move from a source, destination, and optional promotion piece or UCI string.
        """
    @staticmethod
    def from_uci(uci:builtins.str) -> Move:
        r"""
        Create a new move from a UCI string (e.g. "e2e4").
        
        ```python
        >>> rust_chess.Move.from_uci("e2e4")
        Move(e2, e4, None)
        ```
        """
    def get_uci(self) -> builtins.str:
        r"""
        Get the UCI string representation of the move (e.g. "e2e4").
        
        ```python
        >>> move = rust_chess.Move(rust_chess.A2, rust_chess.A4)
        >>> move.get_uci()
        'a2a4'
        ```
        """
    def __str__(self) -> builtins.str:
        r"""
        Get the UCI string representation of the move (e.g. "e2e4").
        
        ```python
        >>> move = rust_chess.Move(rust_chess.A2, rust_chess.A4)
        >>> print(move)
        a2a4
        ```
        """
    def __repr__(self) -> builtins.str:
        r"""
        Get the debug representation of the move (e.g. "Move(e2, e4, None)").
        
        ```python
        >>> move = rust_chess.Move(rust_chess.A2, rust_chess.A4)
        >>> move
        Move(e2, e4, None)
        ```
        """

class Piece:
    r"""
    Piece class
    """
    piece_type: PieceType
    r"""
    Get the piece type of the piece
    """
    color: Color
    r"""
    Get the color of the piece
    """
    def __new__(cls, piece_type:PieceType, color:Color) -> Piece:
        r"""
        Create a new piece from a piece type and color
        """
    def get_index(self) -> builtins.int:
        r"""
        Get the index of the piece (0-5)
        """
    def get_string(self) -> builtins.str:
        r"""
        Convert the piece to a string
        """
    def __str__(self) -> builtins.str:
        r"""
        Convert the piece to a string
        """
    def __repr__(self) -> builtins.str:
        r"""
        Convert the piece to a string
        """

class PieceType:
    r"""
    Piece type enum class.
    
    ```python
    >>> piece = rust_chess.PAWN
    
    >>> print(piece)
    P
    >>> piece == rust_chess.PAWN
    True
    >>> piece == rust_chess.KNIGHT
    False
    >>> piece.get_index()
    0
    >>> piece < rust_chess.KNIGHT
    True
    ```
    """
    def get_index(self) -> builtins.int:
        r"""
        Get the index of the piece (0-5).
        
        ```python
        >>> rust_chess.BISHOP.get_index()
        2
        ```
        """
    def get_string(self, color:Color=...) -> builtins.str:
        r"""
        Convert the piece to a string.
        
        ```python
        >>> rust_chess.PAWN.get_string()
        P
        ```
        """
    def __str__(self) -> builtins.str:
        r"""
        Convert the piece to a string.
        
        ```python
        >>> print(rust_chess.PAWN)
        P
        ```
        """
    def __repr__(self) -> builtins.str:
        r"""
        Convert the piece to a string.
        
        ```python
        >>> rust_chess.PAWN
        P
        ```
        """

class Square:
    r"""
    Square class.
    
    ```python
    >>> square = rust_chess.Square(0)
    >>> square
    a1
    >>> print(square)
    a1
    >>> square == rust_chess.Square("a1")
    True
    >>> square == rust_chess.A1
    True
    >>> square.get_index()
    0
    >>> rust_chess.A4 == 24
    True
    >>> rust_chess.G4.get_rank()
    3
    >>> rust_chess.G4.get_file()
    6
    ```
    """
    def __new__(cls, square:typing.Any) -> Square:
        r"""
        Creates a new square from an integer (0-63) or a string (e.g. "e4").
        
        ```python
        >>> rust_chess.Square(0)
        a1
        >>> rust_chess.Square("e4")
        e4
        ```
        """
    def get_index(self) -> builtins.int:
        r"""
        Get the index of the square (0-63).
        
        ```python
        >>> rust_chess.Square("e4").get_index()
        28
        ```
        """
    @staticmethod
    def from_index(index:builtins.int) -> Square:
        r"""
        Create a new square from an index.
        
        ```python
        >>> rust_chess.Square.from_index(0)
        a1
        ```
        """
    @staticmethod
    def from_rank_file(rank:builtins.int, file:builtins.int) -> Square:
        r"""
        Create a new square from a rank and file.
        
        ```python
        >>> rust_chess.Square.from_rank_file(0, 3)
        d1
        ```
        """
    def get_name(self) -> builtins.str:
        r"""
        Get the name of the square (e.g. "e4").
        
        ```python
        >>> rust_chess.E4.get_name()
        'e4'
        ```
        """
    def __str__(self) -> builtins.str:
        r"""
        Get the name of the square (e.g. "e4"),
        
        ```python
        >>> print(rust_chess.E4)
        e4
        ```
        """
    def __repr__(self) -> builtins.str:
        r"""
        Get the name of the square (e.g. "e4").
        
        ```python
        >>> rust_chess.E4
        e4
        ```
        """
    @staticmethod
    def from_name(square_name:builtins.str) -> Square:
        r"""
        Create a new square from a name (e.g. "e4").
        
        ```python
        >>> rust_chess.Square.from_name("d2")
        d2
        ```
        """
    def __eq__(self, other:typing.Any) -> builtins.bool:
        r"""
        Compare the square to another square or integer.
        
        ```python
        >>> rust_chess.Square("d2") == rust_chess.D2
        True
        >>> rust_chess.Square("d2") == 11
        True
        ```
        """
    def get_rank(self) -> builtins.int:
        r"""
        Get the rank of the square as an integer (0-7).
        
        ```python
        >>> rust_chess.E4.get_rank()
        3
        ```
        """
    def get_file(self) -> builtins.int:
        r"""
        Get the file of the square as an integer (0-7).
        
        ```python
        >>> rust_chess.E4.get_file()
        4
        ```
        """
    def up(self) -> typing.Optional[Square]:
        r"""
        Returns the square above, otherwise None.
        
        ```python
        >>> rust_chess.H5.up()
        h6
        ```
        """
    def down(self) -> typing.Optional[Square]:
        r"""
        Returns the square below, otherwise None.
        
        ```python
        >>> rust_chess.H5.down()
        h4
        ```
        """
    def left(self) -> typing.Optional[Square]:
        r"""
        Returns the square to the left, otherwise None.
        
        ```python
        >>> rust_chess.H5.left()
        g5
        ```
        """
    def right(self) -> typing.Optional[Square]:
        r"""
        Returns the square to the right, otherwise None
        
        ```python
        >>> rust_chess.H5.right()
        
        >>> rust_chess.H5.right() == None
        True
        ```
        """

