import rust_chess as ch

# for i in range(10000):
pawn = ch.Piece.PAWN
print(pawn)
print(pawn.to_index())
print()

square = ch.Square(12)
print(square)
print(square.get_index())
print(square.get_rank())
print(square.get_file())
square2 = ch.Square("E2")
print(square2)
print(square2.get_index())
print(square2.get_rank())
print(square2.get_file())
print(square2.up())
print(square2.down())
print(square2.left())
print(square2.right())
print()

move = ch.Move(ch.Square(12), ch.Square(28))
print(move)
print(move.source)
print(move.dest)
print(move.promotion)
move2 = ch.Move.from_uci("E2E4")
print(move2)
print(move2.source)
print(move2.dest)
print(move2.promotion)
print()

board = ch.Board()
print(board)
print(board.halfmove_clock)
print(board.fullmove_number)
board = ch.Board("rnbqkbnr/ppp1p1pp/5p2/3p4/4P3/3P4/PPP1KPPP/RNBQ1BNR b kq - 1 3")
print(board)
print(board.halfmove_clock)
print(board.fullmove_number)
print(board.is_fifty_moves())
print(board.is_check())
